### ISSUE TITLE
[Feature request] Alingments: AMR <-> AMR  and AMR <-> Sentence

### ISSUE THREAD

**Issue by flipz357** [bjascob/amrlib#3]
Hi,

first, I want to say: You deserve a medal for creating this library. It is the first time I installed an AMR parser without getting a little headache :-). Also it's a nice idea to wrap the noRECAT variant of GSII and ablate all external java preprocessing. I think the noRECAT version may also be more robust.

I have two suggestions of which I think they would be cool to have in an amrlib:

1.  **AMR2sent alignment**: As far as I know, there exist aligners (for instance as pre-processing of JAMR parser), that align AMR nodes to tokens. Since often lemmas of the sentence are projected into the AMR graph, a simple string match, maybe with some additional rules, could make up a first solid method. Maybe there are other methods that are more suitable and also easy-to-use.

2.  **AMR2AMR variable alignment**: This could be useful, e.g., for  computing AMR metrics or enabling sentence retrieval via AMR parsed corpora or sentence similarity computation via AMR. It is an NP hard problem but can be implemented  via hill climbing maximizing triple matching. I have been working on this lately, here is a [repo](https://github.com/flipz357/amr-metric-suite) containing AMR metrics (Smatch and S2match) that are based on this alignment. Both alignments should be quite easy to implement in the lib, since it's all native python. (It could be worthwhile, though, to make the alignment faster, e .g., using cython, since it can be very slow for graphs with many variables)

Alas, these are just suggestions which may or may not be useful to have (in some near or distant future). Again, thanks for your awesome amrlib!

**Comment by bjascob** [comment]
I partially ported the JAMR aligner a while back and I can add this to the lib.  I'd like to find the source for the aligner used for the LDC data but so far haven't been able to.

I'll dig into this a bit next weeek as I'm OOO for a while

**Comment by lujiaying** [comment]
The integrated aligner would be very helpful!

**Comment by bjascob** [comment]
Question to anyone interested in the alignment functionality...

I have a very simple rule based, "word aligner" from JAMR that I ported to python.  This is not the more complicated "span aligner" (ie.. phrases) that is the default alignment method in JAMR.  That code is much more complicated (and in scala) so it would be a fair amount of work to port it into `amrlib`.

Question: Is a simple "word aligner" enough or would this only be useful if we have full span alignments?

There are better span aligners out there (model based) since the early (rule based) JAMR one.  I found the code for an ISI aligner (which may have been used to annotate LDC2020T02).  That code is basically a bunch of scripts to train/run a model using the C++ MGIZA++ library.  It would be a bit of a project, but not completely unreasonable, to make this usable either as part of `amrlib`, or more likely, as a stand-alone lib.

Question: How important (ie.. how much effort is it worth) to include a span aligner and if you think its important, can you give me the use cases for it?

**Comment by lujiaying** [comment]
The reason why I want an aligner in `amrlib` is that "JAMR" is hard to install and somehow hard to integrate with python scripts.

I have seen several papers using JAMR because it is considered as a light aligner compared to model-based ones. So I think as long as the aligner performance is reasonable and easy to install, people like me would love to use it.

**Comment by flipz357** [comment]
I agree with @lujiaying . 

I also think that, from reading the AMR guidelines, there is no "theory of alignment". Therefore, maybe the  token-node alignment may even be a bit more clear-cut than node-span.

E.g. 

```
# The frog jumps.
(j / jump-01
    :arg0 (f /frog)
```

With token alignment it's clear that (f,frog) and (j, jumps) are correct alignments, however both (f, the frog) and (f, frog) can be considered correct in span alignment. 

On the other hand, maybe span has advantages when concepts are really abstract

In sum, I think that a  lightweight  node-token alignment that performs reasonable would be a very good start, since it anchors the AMR in the sentence, which may already be quite helpful for some tasks.

**Comment by bjascob** [comment]
I have updated the master project with Rule Based Word aligner, similar in function to JAMR's word aligner.  If you have comments or bugs, please post a new issue.  (update to pip install to follow).
