### ISSUE TITLE
Trying To Understand Why Certain Inputs Break Parser 

### ISSUE THREAD

**Issue by JosephGatto** [bjascob/amrlib#38]
I am using the T5 parser and noticed that the input 

`Making certain distinctions is imperative in looking back on the past`

Causes the model to return the error 

```
gid=x Unhandled token imperative
Failed to deserialize, snum=0, beam=0
gid=x Unhandled token imperative
Failed to deserialize, snum=0, beam=1
gid=x Unhandled token imperative
Failed to deserialize, snum=0, beam=2
gid=x Unhandled token imperative
Failed to deserialize, snum=0, beam=3

[None]
```

Two questions: 

1) Why does this happen? In general, what kinds of inputs cause such an issue? 
2) Suppose I need the sample parsed, is there anything I can do to get an output? 

Thanks!

**Comment by bjascob** [comment]
This is actually an implementation issue in the deserializer that I hadn't seen before.  In AMR 'interrogative', 'imperative', and 'expressive' are special reserve words used for attributes. Right now the deserializer is tagging them as attributes instead of nodes which they are in your sentence.  Since they're not in the right spot for an attrib it's skipping them.  The model is actually producing correct output going into the deserializer.  

There should be a way to fix this but I'll have to spend a few minutes to figure out the right way to implement it.  I'll post a fix when I get it figured out, probably later today or tomorrow.

The model does occasionally produced improperly formatted output that doesn't deserialize but it's very rare, especially when you're using a beam of 4 (less than 1 in 1K).  If you want to see what's going into the deserializer you can use the flag `ret_raw_gen=True` (see below).  In this case the raw output is properly formatted AMR so you could just use it as is.  However, this won't always be the case. 

Just a little more info to see this...
`stog = amrlib.load_stog_model(model_dir='amrlib/data/model_parse_t5', device='cpu', ret_raw_gen=True)`
`outs = stog.parse_sents(['Making certain distinctions is imperative in looking back on the past'])`
This produces... `( imperative :domain ( distinguish-01 :mod ( certain ) ) :time ( look-01 :ARG1 ( past ) :direction ( back ) ) )`

**Comment by JosephGatto** [comment]
Thanks! Appreciate the quick response. Will look out for your fix.

**Comment by bjascob** [comment]
I pushed a fix (bc6acff).  beam=1 shows 0.815 smatch.
Need to retest with full beam=4 dataset and add the above sentence to the unit test cases.

**Comment by bjascob** [comment]
After fix:
AMR Test Set (beams=4, no-wiki) SMATCH -> P: 0.836,  R: 0.803,  F: 0.819    (0 did not deserialize)

Unit test case added: https://github.com/bjascob/amrlib/commit/519b0af67f9cd57df5b86b85332bd2dd597d93cb

**Comment by JosephGatto** [comment]
I have actually found a few more sentences that break the parser. Not sure why, but figured I'd pass these along. 

```
Input: Researchers have also attempted to estimate the effect of employer-sponsored 401(k) plans on personal saving.

Err Message: 
gid=x Initial node constructed when triples not empty.
Failed to deserialize, snum=0, beam=0
gid=x Initial node constructed when triples not empty.
Failed to deserialize, snum=0, beam=1
gid=x Initial node constructed when triples not empty.
Failed to deserialize, snum=0, beam=2
gid=x Initial node constructed when triples not empty.
Failed to deserialize, snum=0, beam=3
```

```
Input: Soap opera is now getting recognized as a fit topic for analysis.

Err Message: 
gid=x Initial node constructed when triples not empty.
gid=x Missing starting paren for node o/opera
Failed to deserialize, snum=0, beam=0
gid=x Initial node constructed when triples not empty.
gid=x Missing starting paren for node o/opera
Failed to deserialize, snum=0, beam=1
gid=x Initial node constructed when triples not empty.
gid=x Missing starting paren for node o/opera
Failed to deserialize, snum=0, beam=2
gid=x Initial node constructed when triples not empty.
gid=x Missing starting paren for node o/opera
Failed to deserialize, snum=0, beam=3

```

**Comment by bjascob** [comment]
These appear to have minor formatting errors coming off the T5 model and the deserializer can't figure out how to correctly reconstruct them.  Unfortunately there's a bit of random chance in the transformer model training and there's no way to guarantee it won't make small errors.  I tried parsing these with the previous model [parse_t5-v0_1_0](https://github.com/bjascob/amrlib-models/releases/tag/model_parse_t5-v0_1_0) and it parsed them without issue.  You could always use that as a fallback for any failures.

There is also parse_spring model which can still suffer from the same type of issue but it has a completely difference deserializer and anecdotally seems to be a little more resilient to formatting errors.
