### ISSUE TITLE
Smatch Scoring  Discrepancies

### ISSUE THREAD

**Issue by bjascob** [bjascob/amrlib#60]
The [AMRBAR](https://github.com/goodbai-nlp/AMRBART) project noted that smatch scores from amrlib are 0.2 to 0.3 points higher than reported by [amr-evaluation-tool-enhanced](https://github.com/ChunchuanLv/amr-evaluation-tool-enhanced) in this [issue](https://github.com/goodbai-nlp/AMRBART/issues/14).

Scores between amrlib, amr-evaluation-tool-enhanced and the original [snowblink smatch library](https://github.com/snowblink14/smatch) should be compared for differences and variations between runs.  All three libraries rely on the "snowblink" version of smatch for their overall score so they should match within the natural variation of that method.

**Comment by nschneid** [comment]
There's also Smatch++, which uses an ILP solver instead of hill-climbing, so it is supposed to be more accurate. https://github.com/flipz357/smatchpp by @flipz357

**Comment by flipz357** [comment]
Hi,

I think I can explain some of it.

The lower score from the old Smatch script is mainly due to penalizing if the root concept is wrong. Turns out that the penalty is actually desired since the root concept is the focus of an AMR. See also context for more explanation [this recent issue](https://github.com/flipz357/smatchpp/issues/8).

So, **no, higher numbers are not right scores**. 

Importantly, to simply sum up:

Higher numbers due to optimal solving (SMATCH++): **higher numbers are right**

Higher numbers due to ignoring AMR root concept: **higher numbers are wrong**

**Comment by flipz357** [comment]
A bit more on the variation

The differences:

```
Precision: 0.83471, Recall: 0.81098, F-score: 0.82267
Precision: 0.83476, Recall: 0.81103, F-score: 0.82272
Precision: 0.83483, Recall: 0.81109, F-score: 0.82279
```
seem very little and one would think that one shouldn't bother (I used to think like this too), but the issue is that it can be that the real Smatch score is not similar to these numbers. These numbers are result of heuristic. Sometimes it may solve some graph pairs better, and other times other graph pairs. So, on average this can mean little variation. But if you would solve all graph pairs optimally the real Smatch score may be different.
