### ISSUE TITLE
Hi I encounter this issue: TypeError: nop() missing 1 required positional argument: 'it'

### ISSUE THREAD

**Issue by ZhenFox** [bjascob/amrlib#66]
When I run the spaCy extension part code (copied from your post), I encounter this issue: TypeError: nop() missing 1 required positional argument: 'it'

**Comment by bjascob** [comment]
Please provide the traceback.

**Comment by ZhenFox** [comment]
<img width="974" alt="amrlib bug" src="https://github.com/bjascob/amrlib/assets/160564592/4a90c7c1-0b4a-4850-9842-23058c7721e5">
 The screenshot is attached. Thanks for your help!

**Comment by bjascob** [comment]
I don't know what's going on. This works fine for me and it's in the unit tests, so it gets checked every release.
According to the traceback, the issue is with the 3rd party `tqdm` library. You could try commenting out the references to `pbar` (lines 61, 87 and 88). Removing the progress bar won't impact anything since it's probably in disabled mode anyway.
What version of `amrlib` and `tqdm` are you using?

It also could be impacted by the `@torch.no_grad()` statement (line 20).  You can try commenting that out too. That line is not required to run.

**Comment by ZhenFox** [comment]
amrlib is 0.7.1 and tqdm is 4.65.0. 
Is there any wrong with the version? Thank you so much for your help!

Sincerely

**Comment by bjascob** [comment]
You can try updating to the latest amrlib (v0.8.0), but the version you have should work fine.  
You'll need to try commenting out code as I suggested above.

I'm guessing this is an issue with tqdm not working properly in whatever notebook environment you're using. You could run python from a bash prompt and try it there.

If this fixes it, I'd create a simple example of using tqdm outside of amrlib and post the issue to their github page.
